# Generated by Django 5.0.2 on 2024-03-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='static/media/profile_pictures')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vehicle_registration_no', models.CharField(default='', max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('truck_1', '1 ton Truck'), ('truck_1.5', '1.5 ton Truck'), ('truck_2', '2 ton Truck'), ('truck_4', '4 ton Truck')], default='Bike', max_length=100)),
                ('licence_no', models.CharField(default='', max_length=100, unique=True, verbose_name="Driver's Licence Number")),
                ('physical_address', models.CharField(default='', max_length=300)),
                ('driver_licence', models.ImageField(blank=True, null=True, upload_to='static/media/driver_licence')),
                ('vehicle_registration', models.ImageField(blank=True, null=True, upload_to='static/media/vehicle_registration')),
                ('criminal_record_check', models.ImageField(blank=True, null=True, upload_to='static/media/criminal_record_check')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
    ]
