# Generated by Django 5.0.2 on 2024-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_driver_identity_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='criminal_record_check',
            field=models.FileField(blank=True, null=True, upload_to='static/media/criminal_record_check'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_licence',
            field=models.FileField(blank=True, null=True, upload_to='static/media/driver_licence'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='static/media/identity_document'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_registration',
            field=models.FileField(blank=True, null=True, upload_to='static/media/vehicle_registration'),
        ),
    ]
