# Generated by Django 5.0.2 on 2024-04-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_driver_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='driver',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
