# Generated by Django 5.0.2 on 2024-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_userprofile_user_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('truck_1', '1 ton Truck'), ('truck_1.5', '1.5 ton Truck'), ('truck_2', '2 ton Truck'), ('truck_4', '4 ton Truck')], default='Bike', max_length=100),
        ),
    ]
