# Generated by Django 5.0.2 on 2024-07-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_alter_driver_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="acceptance_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
