# Generated by Django 5.0.2 on 2024-02-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_user_is_email_confirmed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerification',
            new_name='EmailVerificationToken',
        ),
    ]
