# Generated by Django 5.0.2 on 2024-02-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_rename_emailverification_emailverificationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
