# Generated by Django 5.0.2 on 2024-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_rename_created_at_trip_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
