# Generated by Django 5.0.2 on 2024-02-21 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_trip_description_trip_number_of_helpers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_type',
            field=models.DateTimeField(blank=True, default=datetime.date),
        ),
    ]
