# Generated by Django 5.0.2 on 2024-02-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trip_pickup_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='pickup_type',
        ),
    ]
