# Generated by Django 5.0.2 on 2024-02-21 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_remove_trip_pickup_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='description',
            new_name='load_description',
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_type',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
