# Generated by Django 5.0.2 on 2024-02-21 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_rename_description_trip_load_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_type',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
