# Generated by Django 5.0.2 on 2024-02-21 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_alter_trip_pickup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.pickuplocation'),
        ),
    ]
