# Generated by Django 5.0.2 on 2024-02-21 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_alter_trip_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
