# Generated by Django 5.0.2 on 2024-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_alter_trip_created_alter_trip_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
