# Generated by Django 5.0.2 on 2024-02-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_alter_trip_pickup_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='pickup_type',
            new_name='pickup_time',
        ),
    ]
