# Generated by Django 5.0.2 on 2024-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_rename_pickup_type_trip_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(max_length=300),
        ),
    ]
