# Generated by Django 5.0.2 on 2024-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_alter_trip_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='number_floors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Enter your full name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
