# Generated by Django 5.0.2 on 2024-02-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_driver_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('truck_1', '1 ton Truck'), ('truck_1.5', '1.5 ton Truck'), ('truck_2', '2 ton Truck'), ('truck_4', '4 ton Truck')], default='bike'),
        ),
    ]
