# Generated by Django 5.0.2 on 2024-02-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0029_alter_driver_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='physical_address',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
