# Generated by Django 5.0.2 on 2024-02-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0030_remove_driver_physical_address_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='physical_address',
        ),
        migrations.AddField(
            model_name='driver',
            name='physical_address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
