# Generated by Django 5.0.2 on 2024-03-27 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_driver_criminal_record_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_time', models.DateTimeField(auto_now=True)),
                ('dropoff_contact_number', models.CharField(max_length=20, null=True)),
                ('load_description', models.TextField(default='', max_length=500)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('truck_1', '1 ton Truck'), ('truck_1.5', '1.5 ton Truck'), ('truck_2', '2 ton Truck'), ('truck_4', '4 ton Truck')], max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('IN_PROGRESS', 'IN_PROGRESS')], default='REQUESTED', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_floors', models.IntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_as_driver', to='authentication.driver')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.driver')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Payment',
                'verbose_name_plural': 'Trip Payments',
            },
        ),
    ]
