# Generated by Django 5.0.2 on 2024-03-01 12:31

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vehicle_registration', models.CharField(default='', max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('truck_1', '1 ton Truck'), ('truck_1.5', '1.5 ton Truck'), ('truck_2', '2 ton Truck'), ('truck_4', '4 ton Truck')], default='Bike', max_length=100)),
                ('licence_no', models.CharField(default='', max_length=100, unique=True, verbose_name="Driver's Licence Number")),
                ('physical_address', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
            bases=('trips.user',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.CharField(max_length=300)),
                ('dropoff_location', models.CharField(max_length=300)),
                ('pickup_time', models.DateTimeField(default=datetime.datetime.now)),
                ('load_description', models.TextField(default='', max_length=500)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('van', 'Van'), ('truck_1', '1 ton Truck'), ('truck_1.5', '1.5 ton Truck'), ('truck_2', '2 ton Truck'), ('truck_4', '4 ton Truck')], max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('IN_PROGRESS', 'IN_PROGRESS')], default='REQUESTED', max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_floors', models.IntegerField(default=0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_as_user', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_as_driver', to='trips.driver')),
            ],
        ),
    ]
