# Generated by Django 5.0.2 on 2024-04-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_phone_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_phone_number',
        ),
    ]
