# Generated by Django 5.0.2 on 2024-04-30 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_userprofile_user_user_profile_picture_and_more'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_phone_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_phone_number',
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(blank=True, max_length=8, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='trips.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='TripPayment',
        ),
    ]
