# Generated by Django 5.0.2 on 2024-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
