# Generated by Django 5.0.2 on 2024-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trippayment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippayment',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
