# Generated by Django 5.0.2 on 2024-03-04 07:19

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.UUIDField(default=uuid.uuid4,editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
