# Generated by Django 5.0.2 on 2024-08-02 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0006_alter_trip_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="compensation_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="trips.trip",
            ),
        ),
    ]
