# Generated by Django 5.0.2 on 2024-08-02 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0007_payment_compensation_amount_payment_net_amount_and_more"),
    ]

    operations = []
