# Generated by Django 5.0.2 on 2024-03-04 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_UUID_Field'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
