# Generated by Django 5.0.2 on 2024-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_user_is_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
