# Generated by Django 5.0.2 on 2024-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_alter_trip_driver_alter_trip_user_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
