# Generated by Django 5.0.2 on 2024-03-11 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.date(2024, 3, 11)),
        ),
    ]
