# Generated by Django 5.0.2 on 2024-03-11 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_dropofflocation_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
