# Generated by Django 5.0.2 on 2024-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropOffLocation',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.DeleteModel(
            name='PickupLocation',
        ),
        migrations.AddField(
            model_name='driver',
            name='criminal_record_check',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/criminal_record_check'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_licence',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/driver_licence'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_registration_no',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_registration',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/vehicle_registration'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/profile_pictures'),
        ),
    ]
